M48
; DRILL file {KiCad 7.0.10} date Thu Jan 18 13:18:53 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-18T13:18:53-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X2.8Y-2.1
X3.2Y-1.5
X3.2Y-1.6
X3.6Y-1.5
T2
X2.9Y-1.4
X2.9984Y-1.4
M30
